### ISSUE TITLE
Mutation rate per subclone

### ISSUE THREAD

**Issue by caravagn** [T-Heide/TEMULATOR#2]
Hey, is it possible to change the mutation rate among subclones? Say i can increase the mutations rate in a hypermutant subclone, and then maybe revert it (in a 3-clones model).

**Comment by caravagn** [comment]
I guess from here https://t-heide.github.io/TEMULATOR/reference/simulateTumour.html that the snippet below would just do this no?

```
simulateTumour(
  mutation_rates = c(16, 100, 16),
  clone_start_times = c(0, 100, 200)
)
```

**Comment by caravagn** [comment]
In this case, could it be possible to "snapshot" the simulation at multiple time-points instead than just at the end?

Say at timepoints 80, 140 and 250 for instance. And in general what would be the value of father to have the subclones to be nested one inside another?

**Comment by T-Heide** [comment]
I have added some examples showing how this can be done to the vignette (https://t-heide.github.io/TEMULATOR/articles/time_series.html#sequencing-samples-showing-a-selective-sweep-1).
